/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MajorRouteImport } from './routes/major'
import { Route as MapRouteImport } from './routes/map'
import { Route as McdRouteImport } from './routes/mcd'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ComplaintIdRouteImport } from './routes/complaint.$id'
import { Route as ApiAuthoritiesIndexRouteImport } from './routes/api/authorities/index'
import { Route as ApiComplaintsIndexRouteImport } from './routes/api/complaints/index'
import { Route as ApiComplaintsEscalateOverdueRouteImport } from './routes/api/complaints/escalate-overdue'
import { Route as ApiComplaintsMajorRouteImport } from './routes/api/complaints/major'
import { Route as ApiComplaintsNearbyRouteImport } from './routes/api/complaints/nearby'
import { Route as ApiEvidenceSplatRouteImport } from './routes/api/evidence/$'
import { Route as ApiEvidenceUploadRouteImport } from './routes/api/evidence/upload'
import { Route as ApiComplaintsIdIndexRouteImport } from './routes/api/complaints/$id/index'
import { Route as ApiComplaintsIdStatusRouteImport } from './routes/api/complaints/$id/status'
import { Route as ApiComplaintsIdRoutingIndexRouteImport } from './routes/api/complaints/$id/routing/index'
import { Route as ApiComplaintsIdRoutingReassignRouteImport } from './routes/api/complaints/$id/routing/reassign'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MajorRoute = MajorRouteImport.update({
  id: '/major',
  path: '/major',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const McdRoute = McdRouteImport.update({
  id: '/mcd',
  path: '/mcd',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintIdRoute = ComplaintIdRouteImport.update({
  id: '/complaint/$id',
  path: '/complaint/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthoritiesIndexRoute = ApiAuthoritiesIndexRouteImport.update({
  id: '/api/authorities/',
  path: '/api/authorities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComplaintsIndexRoute = ApiComplaintsIndexRouteImport.update({
  id: '/api/complaints/',
  path: '/api/complaints/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComplaintsEscalateOverdueRoute =
  ApiComplaintsEscalateOverdueRouteImport.update({
    id: '/api/complaints/escalate-overdue',
    path: '/api/complaints/escalate-overdue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiComplaintsMajorRoute = ApiComplaintsMajorRouteImport.update({
  id: '/api/complaints/major',
  path: '/api/complaints/major',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComplaintsNearbyRoute = ApiComplaintsNearbyRouteImport.update({
  id: '/api/complaints/nearby',
  path: '/api/complaints/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvidenceSplatRoute = ApiEvidenceSplatRouteImport.update({
  id: '/api/evidence/$',
  path: '/api/evidence/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvidenceUploadRoute = ApiEvidenceUploadRouteImport.update({
  id: '/api/evidence/upload',
  path: '/api/evidence/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComplaintsIdIndexRoute = ApiComplaintsIdIndexRouteImport.update({
  id: '/api/complaints/$id/',
  path: '/api/complaints/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComplaintsIdStatusRoute = ApiComplaintsIdStatusRouteImport.update({
  id: '/api/complaints/$id/status',
  path: '/api/complaints/$id/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComplaintsIdRoutingIndexRoute =
  ApiComplaintsIdRoutingIndexRouteImport.update({
    id: '/api/complaints/$id/routing/',
    path: '/api/complaints/$id/routing/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiComplaintsIdRoutingReassignRoute =
  ApiComplaintsIdRoutingReassignRouteImport.update({
    id: '/api/complaints/$id/routing/reassign',
    path: '/api/complaints/$id/routing/reassign',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/major': typeof MajorRoute
  '/map': typeof MapRoute
  '/mcd': typeof McdRoute
  '/report': typeof ReportRoute
  '/complaint/$id': typeof ComplaintIdRoute
  '/api/complaints/escalate-overdue': typeof ApiComplaintsEscalateOverdueRoute
  '/api/complaints/major': typeof ApiComplaintsMajorRoute
  '/api/complaints/nearby': typeof ApiComplaintsNearbyRoute
  '/api/evidence/$': typeof ApiEvidenceSplatRoute
  '/api/evidence/upload': typeof ApiEvidenceUploadRoute
  '/api/authorities/': typeof ApiAuthoritiesIndexRoute
  '/api/complaints/': typeof ApiComplaintsIndexRoute
  '/api/complaints/$id/status': typeof ApiComplaintsIdStatusRoute
  '/api/complaints/$id/': typeof ApiComplaintsIdIndexRoute
  '/api/complaints/$id/routing/reassign': typeof ApiComplaintsIdRoutingReassignRoute
  '/api/complaints/$id/routing/': typeof ApiComplaintsIdRoutingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/major': typeof MajorRoute
  '/map': typeof MapRoute
  '/mcd': typeof McdRoute
  '/report': typeof ReportRoute
  '/complaint/$id': typeof ComplaintIdRoute
  '/api/complaints/escalate-overdue': typeof ApiComplaintsEscalateOverdueRoute
  '/api/complaints/major': typeof ApiComplaintsMajorRoute
  '/api/complaints/nearby': typeof ApiComplaintsNearbyRoute
  '/api/evidence/$': typeof ApiEvidenceSplatRoute
  '/api/evidence/upload': typeof ApiEvidenceUploadRoute
  '/api/authorities': typeof ApiAuthoritiesIndexRoute
  '/api/complaints': typeof ApiComplaintsIndexRoute
  '/api/complaints/$id/status': typeof ApiComplaintsIdStatusRoute
  '/api/complaints/$id': typeof ApiComplaintsIdIndexRoute
  '/api/complaints/$id/routing/reassign': typeof ApiComplaintsIdRoutingReassignRoute
  '/api/complaints/$id/routing': typeof ApiComplaintsIdRoutingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/major': typeof MajorRoute
  '/map': typeof MapRoute
  '/mcd': typeof McdRoute
  '/report': typeof ReportRoute
  '/complaint/$id': typeof ComplaintIdRoute
  '/api/complaints/escalate-overdue': typeof ApiComplaintsEscalateOverdueRoute
  '/api/complaints/major': typeof ApiComplaintsMajorRoute
  '/api/complaints/nearby': typeof ApiComplaintsNearbyRoute
  '/api/evidence/$': typeof ApiEvidenceSplatRoute
  '/api/evidence/upload': typeof ApiEvidenceUploadRoute
  '/api/authorities/': typeof ApiAuthoritiesIndexRoute
  '/api/complaints/': typeof ApiComplaintsIndexRoute
  '/api/complaints/$id/status': typeof ApiComplaintsIdStatusRoute
  '/api/complaints/$id/': typeof ApiComplaintsIdIndexRoute
  '/api/complaints/$id/routing/reassign': typeof ApiComplaintsIdRoutingReassignRoute
  '/api/complaints/$id/routing/': typeof ApiComplaintsIdRoutingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/major'
    | '/map'
    | '/mcd'
    | '/report'
    | '/complaint/$id'
    | '/api/complaints/escalate-overdue'
    | '/api/complaints/major'
    | '/api/complaints/nearby'
    | '/api/evidence/$'
    | '/api/evidence/upload'
    | '/api/authorities/'
    | '/api/complaints/'
    | '/api/complaints/$id/status'
    | '/api/complaints/$id/'
    | '/api/complaints/$id/routing/reassign'
    | '/api/complaints/$id/routing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/major'
    | '/map'
    | '/mcd'
    | '/report'
    | '/complaint/$id'
    | '/api/complaints/escalate-overdue'
    | '/api/complaints/major'
    | '/api/complaints/nearby'
    | '/api/evidence/$'
    | '/api/evidence/upload'
    | '/api/authorities'
    | '/api/complaints'
    | '/api/complaints/$id/status'
    | '/api/complaints/$id'
    | '/api/complaints/$id/routing/reassign'
    | '/api/complaints/$id/routing'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/major'
    | '/map'
    | '/mcd'
    | '/report'
    | '/complaint/$id'
    | '/api/complaints/escalate-overdue'
    | '/api/complaints/major'
    | '/api/complaints/nearby'
    | '/api/evidence/$'
    | '/api/evidence/upload'
    | '/api/authorities/'
    | '/api/complaints/'
    | '/api/complaints/$id/status'
    | '/api/complaints/$id/'
    | '/api/complaints/$id/routing/reassign'
    | '/api/complaints/$id/routing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  MajorRoute: typeof MajorRoute
  MapRoute: typeof MapRoute
  McdRoute: typeof McdRoute
  ReportRoute: typeof ReportRoute
  ComplaintIdRoute: typeof ComplaintIdRoute
  ApiComplaintsEscalateOverdueRoute: typeof ApiComplaintsEscalateOverdueRoute
  ApiComplaintsMajorRoute: typeof ApiComplaintsMajorRoute
  ApiComplaintsNearbyRoute: typeof ApiComplaintsNearbyRoute
  ApiEvidenceSplatRoute: typeof ApiEvidenceSplatRoute
  ApiEvidenceUploadRoute: typeof ApiEvidenceUploadRoute
  ApiAuthoritiesIndexRoute: typeof ApiAuthoritiesIndexRoute
  ApiComplaintsIndexRoute: typeof ApiComplaintsIndexRoute
  ApiComplaintsIdStatusRoute: typeof ApiComplaintsIdStatusRoute
  ApiComplaintsIdIndexRoute: typeof ApiComplaintsIdIndexRoute
  ApiComplaintsIdRoutingReassignRoute: typeof ApiComplaintsIdRoutingReassignRoute
  ApiComplaintsIdRoutingIndexRoute: typeof ApiComplaintsIdRoutingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/major': {
      id: '/major'
      path: '/major'
      fullPath: '/major'
      preLoaderRoute: typeof MajorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcd': {
      id: '/mcd'
      path: '/mcd'
      fullPath: '/mcd'
      preLoaderRoute: typeof McdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaint/$id': {
      id: '/complaint/$id'
      path: '/complaint/$id'
      fullPath: '/complaint/$id'
      preLoaderRoute: typeof ComplaintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/authorities/': {
      id: '/api/authorities/'
      path: '/api/authorities'
      fullPath: '/api/authorities/'
      preLoaderRoute: typeof ApiAuthoritiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/complaints/': {
      id: '/api/complaints/'
      path: '/api/complaints'
      fullPath: '/api/complaints/'
      preLoaderRoute: typeof ApiComplaintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/complaints/escalate-overdue': {
      id: '/api/complaints/escalate-overdue'
      path: '/api/complaints/escalate-overdue'
      fullPath: '/api/complaints/escalate-overdue'
      preLoaderRoute: typeof ApiComplaintsEscalateOverdueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/complaints/major': {
      id: '/api/complaints/major'
      path: '/api/complaints/major'
      fullPath: '/api/complaints/major'
      preLoaderRoute: typeof ApiComplaintsMajorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/complaints/nearby': {
      id: '/api/complaints/nearby'
      path: '/api/complaints/nearby'
      fullPath: '/api/complaints/nearby'
      preLoaderRoute: typeof ApiComplaintsNearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evidence/$': {
      id: '/api/evidence/$'
      path: '/api/evidence/$'
      fullPath: '/api/evidence/$'
      preLoaderRoute: typeof ApiEvidenceSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evidence/upload': {
      id: '/api/evidence/upload'
      path: '/api/evidence/upload'
      fullPath: '/api/evidence/upload'
      preLoaderRoute: typeof ApiEvidenceUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/complaints/$id/': {
      id: '/api/complaints/$id/'
      path: '/api/complaints/$id'
      fullPath: '/api/complaints/$id/'
      preLoaderRoute: typeof ApiComplaintsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/complaints/$id/status': {
      id: '/api/complaints/$id/status'
      path: '/api/complaints/$id/status'
      fullPath: '/api/complaints/$id/status'
      preLoaderRoute: typeof ApiComplaintsIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/complaints/$id/routing/': {
      id: '/api/complaints/$id/routing/'
      path: '/api/complaints/$id/routing'
      fullPath: '/api/complaints/$id/routing/'
      preLoaderRoute: typeof ApiComplaintsIdRoutingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/complaints/$id/routing/reassign': {
      id: '/api/complaints/$id/routing/reassign'
      path: '/api/complaints/$id/routing/reassign'
      fullPath: '/api/complaints/$id/routing/reassign'
      preLoaderRoute: typeof ApiComplaintsIdRoutingReassignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  MajorRoute: MajorRoute,
  MapRoute: MapRoute,
  McdRoute: McdRoute,
  ReportRoute: ReportRoute,
  ComplaintIdRoute: ComplaintIdRoute,
  ApiComplaintsEscalateOverdueRoute: ApiComplaintsEscalateOverdueRoute,
  ApiComplaintsMajorRoute: ApiComplaintsMajorRoute,
  ApiComplaintsNearbyRoute: ApiComplaintsNearbyRoute,
  ApiEvidenceSplatRoute: ApiEvidenceSplatRoute,
  ApiEvidenceUploadRoute: ApiEvidenceUploadRoute,
  ApiAuthoritiesIndexRoute: ApiAuthoritiesIndexRoute,
  ApiComplaintsIndexRoute: ApiComplaintsIndexRoute,
  ApiComplaintsIdStatusRoute: ApiComplaintsIdStatusRoute,
  ApiComplaintsIdIndexRoute: ApiComplaintsIdIndexRoute,
  ApiComplaintsIdRoutingReassignRoute: ApiComplaintsIdRoutingReassignRoute,
  ApiComplaintsIdRoutingIndexRoute: ApiComplaintsIdRoutingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
